# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: "Execução Manual"

# regras de disparo (gatilho/trigger)
# gatilho de exec manual = workflow_dispatch
 
on:
  workflow_dispatch:


  # trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests: #criação do jobs

  #maquina que o job vai executar, outras procurar em actions/runner-images 
    runs-on: ubuntu-latest

  # passos que o job vai executar
    steps: 
    
    # clone do projeto
    - name: Checkout code
      uses: actions/checkout@v2
    # instalação do Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.x' # ou a versão que você preferir
    # instalação do yarn
    - name: Install Yarn
      run: npm install -g yarn

    # instalação das dependências do projeto
    - name: Install dependencies
      run: yarn

    # instalação do playwright
    - name: Install Playwright
      run: yarn playwright install
       
    # execução dos testes e2e
    - name: Run E2E tests
      run: yarn run e2e

    # --- NOVA ACTION 1: Publica o Resumo dos Testes (JUnit) para a aba "Tests" ---
    # Isso criará uma aba "Tests" na sua execução de workflow no GitHub
    - name: Publish Test Results (JUnit)
      uses: dorny/test-reporter@v1 # Use a versão mais recente se houver
      if: always() # Garante que os resultados serão publicados mesmo se os testes falharem
      with:
        name: Playwright E2E Tests # Nome da execução de teste que aparecerá na aba "Tests"
        path: results.xml # O caminho para o seu arquivo JUnit XML
        reporter: playwright-junit # Tipo de reporter, o playwright-junit é específico para o formato do playwright

    # --- NOVA ACTION 2: Publica o Relatório HTML Completo do Playwright como Artefato ---
    # Isso permitirá que você baixe o relatório HTML interativo completo
    - name: Upload Playwright HTML Report
      uses: actions/upload-artifact@v3 # Use a versão mais recente
      if: always() # Garante que o relatório será carregado mesmo se os testes falharem
      with:
        name: playwright-html-report # Nome do artefato
        path: playwright-report # O diretório onde o Playwright salva o relatório HTML
        retention-days: 5 # Opcional: quantos dias o artefato deve ser mantido (padrão é 90)
